// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABCRXCPxOwK6ufwcGHrrW09RuC5Ro28lk',
    appId: '1:480357877765:web:c93c0a35d40f3bd8cdf46c',
    messagingSenderId: '480357877765',
    projectId: 'cw06-5ef2e',
    authDomain: 'cw06-5ef2e.firebaseapp.com',
    storageBucket: 'cw06-5ef2e.firebasestorage.app',
    measurementId: 'G-CB4MHKBH6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyCbgxoD3ioUCgRgXryNXpxMIvb_XHfMI',
    appId: '1:480357877765:android:498677a45ef13af6cdf46c',
    messagingSenderId: '480357877765',
    projectId: 'cw06-5ef2e',
    storageBucket: 'cw06-5ef2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwkiCFanerMedIow59SOp0Xv5xXtJMBrI',
    appId: '1:480357877765:ios:25cdd7f516baadcdcdf46c',
    messagingSenderId: '480357877765',
    projectId: 'cw06-5ef2e',
    storageBucket: 'cw06-5ef2e.firebasestorage.app',
    iosBundleId: 'com.example.cw06',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwkiCFanerMedIow59SOp0Xv5xXtJMBrI',
    appId: '1:480357877765:ios:25cdd7f516baadcdcdf46c',
    messagingSenderId: '480357877765',
    projectId: 'cw06-5ef2e',
    storageBucket: 'cw06-5ef2e.firebasestorage.app',
    iosBundleId: 'com.example.cw06',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABCRXCPxOwK6ufwcGHrrW09RuC5Ro28lk',
    appId: '1:480357877765:web:aaf7679e90ed8692cdf46c',
    messagingSenderId: '480357877765',
    projectId: 'cw06-5ef2e',
    authDomain: 'cw06-5ef2e.firebaseapp.com',
    storageBucket: 'cw06-5ef2e.firebasestorage.app',
    measurementId: 'G-C6F64E4FH3',
  );
}
